config/routes.rb
Rails.application.routes.draw do
   devise_for :users
  root to: "home#index"
  
  resources :recettes
  resources :users
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recette.rb
class Recette < ApplicationRecord
  belongs_to :user
  attachment :image


  with_options presence: true do
     validates :title
     validates :memo
     validates :image
    end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :recettes, dependent: :destroy
  attachment :profile_image
   
  validates :user_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
end

private
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recettes = Recette.all.order(created_at: :desc)
    @users = User.all
  end

end

app/controllers/recettes_controller.rb
class RecettesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @recette = Recette.new
  end

  def create
    @recette = Recette.new(recette_params)
    @recette.user_id = current_user.id
    if @recette.save
    redirect_to recette_path(@recette), notice: '投稿しました'
    else
      render :new
    end
  end

  def index 
    @recettes = Recette.all.order(created_at: :desc)
    @recettes = Recette.page(params[:page]).per(6)
  end

  def show
    @recette = Recette.find(params[:id])
  end

  def edit
    @recette = Recette.find(params[:id])
    if @recette.user != current_user
      redirect_to root_path, alert: '不正なアクセスです!!!!!'
    end
  end
 
  def update
    @recette = Recette.find(params[:id])
    if @recette.update(recette_params)
    redirect_to recette_path(@recette), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    recette = Recette.find(params[:id])
    recette.destroy
    redirect_to user_path(recette.user)
  end 

  private
    
  def recette_params
      params.require(:recette).permit(:title, :memo, :image)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path, alert: '不正なアクセスです!!!!!'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
  end
  

  private
    def user_params
      params.require(:user).permit(:user_name, :email, :profile, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recette_helper.rb
module RecetteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: monospace;">Sweets_Room</strong>
        </p>
      </div>
          <% if user_signed_in? %>
           <%= link_to "こんにちは、#{current_user.user_name}さん", user_path(current_user), class: :greeting__link%>
          <% end %>
      <div class="columns is-centered">
        <div class="column is-5">
          
          
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recettes.each do |recette| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recette_path(recette) do %>
                  <%= attachment_image_tag recette, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag recette.user, :profile_image, :fill, 50,50, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to recette.user.user_name, user_path(recette.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= recette.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
　

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetsRoom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-white">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: monospace;">Sweets_Room</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
                
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "作り方一覧", recettes_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "投稿", new_recette_path, class: "navbar-item button is-warning is-light" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "みんなのページ", users_path, class: " button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "作り方一覧", recettes_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "みんなのページ", users_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/recettes/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ルセット編集
      </h1>
    </div>
  </div>
</section>

<% if @recette.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recette.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recette.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recette do |f| %>
          <div class="field">
            <%= f.label :title, "料理名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :memo, "作り方", class: "label" %>
            <%= f.text_area :memo, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-danger is-outlined" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recettes/index.html.erb
 <section class="hero is-small is-primary">
  <div class="hero-body">
    <p class="title">
      作り方と写真一覧
    </p>
    
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recettes.each do |recette| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recette_path(recette) do %>
                  <%= attachment_image_tag recette, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag recette.user, :profile_image, :fill, 50,50, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to recette.user.user_name, user_path(recette.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= recette.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<%= paginate @recettes %>

app/views/recettes/new.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規ルセット作成
      </h1>
    </div>
  </div>
</section>


<% if @recette.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recette.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @recette.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recette do |f| %>
          <div class="field">
            <%= f.label :title, "名称", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :memo, "作り方", class: "label" %>
            <%= f.text_area :memo, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-danger is-outlined" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recettes/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ルセット詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @recette, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @recette.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>作り方</th>
                </tr>
                <tr>
                  <td><%= simple_format @recette.memo %></td>
                </tr>
              </table>
              <% if @recette.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_recette_path(@recette), class: "button is-danger is-outlined" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
             <%= @recette.user.user_name %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @recette.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@recette.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @recette.user.user_name %> さんのページへ
            <% end %>      
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :user_name, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-danger is-outlined" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        みんなのページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image,:fill, 100,100, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.user_name, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.recettes.count %> 
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイルーム
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, :fill, 100,100, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.user_name %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-danger is-outlined" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recettes.each do |recette| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recette_path(recette) do %>
                  <%= attachment_image_tag recette, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recette_path(recette), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_recette_path(recette), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      編集する
                    <% end %>
                    <%= link_to recette_path(recette), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= recette.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
 